server:
  port: 8083

spring:
  application:
    name: api-gateway
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/webshop
          jwk-set-uri: http://localhost:8181/realms/webshop/protocol/openid-connect/certs
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: product
          uri: lb://product
          predicates:
            - Path=/api/products/**
        - id: payment
          uri: lb://payment
          predicates:
            - Path=/api/payment/**
        - id: order
          uri: lb://order
          predicates:
            - Path=/api/order/**
        - id: eureka
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true
