server:
  port: 8088
spring:
  application:
    name: webshop-assistant
  ai:
    openai:
      api-key: sk-proj-0pf0s7Is2VHK8aqSNyiTT3BlbkFJFp9RZhDqb4lrIlVxzuwc
      chat:
        options:
          model: gpt-3.5-turbo
